on:
  push:
   branches: [master]

defaults:
  run:
    working-directory: jsx


jobs:

  build-archive-artifacts:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v2
      - name: Use Node.js 14.x
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - name: Install dependencies
        run: npm install    
      - name: Generate build
        run: npm run build
      # Share artifact inside workflow
      - name: Share artifact inside workflow
        uses: actions/download-artifact@v2
        with:
          name: react-git-gen-build
          path: build
 
